# Generated by Django 3.2.3 on 2021-05-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0004_profile_company'),
        ('MainApp', '0005_eventuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventUser',
        ),
    ]
