# Generated by Django 3.2.3 on 2021-05-24 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_auto_20210524_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 24, 18, 43, 34, 282998)),
        ),
    ]
